GitHub Action: upload html output to github pages

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,11 +28,19 @@ jobs:
       - name: Check for output
         run: ls -Rla doc/build/
 
-      # Create an artifact of the html output.
-      - uses: actions/upload-artifact@v3
-        with:
-          name: Docs-HTML
-          path: doc/build/html/
+      # Publish built docs to gh-pages branch.
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/BAMresearch/analyse_dls_with_contin.git --branch gh-pages --single-branch gh-pages
+          cp -R doc/build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Updated documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
 
 #      - name: Install LaTeX packages
 #        run: |
